theme: jekyll-theme-minimal
title: Parla con me
description:
  segni selezionati della LIS (Lingua dei Segni Italiana) per parlare con i neonati.
  Ispirato dal [libro di Nancy Cadjan](https://www.amazon.it/Mamma-parla-segni-comunicare-bambino/dp/8860523796).
  I video vengono da https://www.spreadthesign.com
